# Generated by Django 4.1.3 on 2022-11-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
